replicaCount: 5
image:
  repository: cjoseph246/sample-microservice
  tag: v0.1
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 256Mi