replicaCount: 5
image:
  repository: cjoseph246/sample-microservice
  tag: v0.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 256Mi