apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::062989738166:role/eks-cluster-cluster-20250404183045393700000005
      username: eks-admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::062989738166:user/Chuck
      username: Chuck
      groups:
        - system:masters