name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: cjoseph246/sample-microservice
      VALUES_PATH: infra/apps/sample-microservice/chart/values.yaml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t $IMAGE_NAME:latest ./sample-microservice
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      - name: Update image tag in Helm values.yaml
        run: |
          echo "Updating image.tag in $VALUES_PATH to $IMAGE_TAG"
          yq e -i ".image.tag = \"$IMAGE_TAG\"" "$VALUES_PATH"

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add "$VALUES_PATH"
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
