apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-microservice.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "sample-microservice.name" . }}
