apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.12.0
    helm:
      values: |
        clusterName: eks-cluster
        serviceAccount:
          name: aws-load-balancer-controller
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::062989738166:role/aws-load-balancer-controller-irsa
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true